[package]
name = "spv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default     = ["gpu"]

[dependencies]
rspirv      = "^0.11.0"
glam        = "^0.20.5"
slab        = "^0.4.6"
either      = "^1.6.1"
gpu         = { path = "../gpu", optional=true }

[dev-dependencies]
shaderc     = "*"
bytemuck    = "*"
winit       = "0.26.1"
env_logger  = "0.9.0"
image       = "0.24.1"

[[example]]
name        = "basic"

[[example]]
name        = "uniform"

[[example]]
name        = "help"