#version 450

layout(local_size_x = 1) in;

layout(set = 0, binding = 0) buffer Data {
    uint[] indices;
};

uint iterations(uint n) {
    if (n == 0) {
        return 0;
    }

    uint i = 0;
    while (n != 1) {
        if (mod(n, 2) == 0) {
            n = n / 2;
        } else {
            n = (3 * n) + 1;
        }
        i++;
    }

    return i;
}

void main() {
    uint index = gl_GlobalInvocationID.x;
    indices[index] = iterations(index);
}